# Generated by Django 3.2.9 on 2021-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_city', models.CharField(max_length=200)),
                ('school_state', models.CharField(max_length=200)),
                ('school_rank', models.IntegerField()),
                ('school_type', models.CharField(max_length=200)),
                ('school_des', models.TextField()),
            ],
        ),
    ]
